export const DEFAULT_CENTER_LATITUDE = 25.036359;
export const DEFAULT_CENTER_LONGITUDE = 121.522635;
export const DEFAULT_MAP_TYPE = "terrain";
export const DEFAULT_ZOOM_LEVEL = 12;

export const DEFAULT_PROPERTY_NAME_FILL_COLOR = "fill";
export const DEFAULT_PROPERTY_NAME_METADATA = "metadata";

export const DEFAULT_STYLE_FILL_OPACITY = 0.5;
export const DEFAULT_STYLE_STROKE_WEIGHT = 1;
