export const MUTATION_MAP_SET_MAP_INSTANCE = "MUTATION_MAP_SET_MAP_INSTANCE";
export const MUTATION_MAP_SET_SELECTED_GRID = "MUTATION_MAP_SET_SELECTED_GRID";
export const MUTATION_MAP_SET_SELECTED_WIDGET_TAB = "MUTATION_MAP_SET_SELECTED_WIDGET_TAB";
